#!/bin/bash
#SET the web password from inside terraform
#user webuser
WEBPASS='myrandomstring!@!' # TODO: need to pull this value from secrets. Change this to what oyu want
WORKDIR="/root"
sudo apt-get update

# Ignore any intereactive dialog when doing upgrade
# sudo DEBIAN_FRONTEND=noninteractive sh -c 'echo $DEBIAN_FRONTEND'
DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -yq 

#install git
apt install git -y && \

# work from the home directory and clone tpot
#cd $ADMINHOME
cd $WORKDIR
git clone https://github.com/telekom-security/tpotce.git && \

# make a copy of the default tpot.conf file. 
#cp ./tpotce/iso/installer/tpot.conf.dist ./tpot.conf
cp $WORKDIR/tpotce/iso/installer/tpot.conf.dist $WORKDIR/tpot.conf && \
# set the password to random string generated by terraform
sed "s/myCONF_WEB_PW[^ ]*/myCONF_WEB_PW='$WEBPASS'/g" -i $WORKDIR/tpot.conf && \

cd $WORKDIR/tpotce
./install.sh --type=auto --conf="$WORKDIR/tpot.conf" && \
systemctl start tpot && \
systemctl enable tpot && \
rm $WORKDIR/tpot.conf && \
/sbin/reboot
